[package]
distribution = "2201.12.0"
org = "ballerinax"
name = "paypal.subscriptions"
version = "1.0.0"
license = ["Apache-2.0"]
authors = ["Ballerina"]
keywords = ["PayPal", "Subscriptions", "Plans","Billing", "Payments", "Recurring", "Connector"]
icon = "icon.png"

repository = "https://github.com/ballerina-platform/module-ballerinax-paypal.subscriptions"

[build-options]
observabilityIncluded = true

[platform.java21]
graalvmCompatible = true
